### ISSUE TITLE
Issue on page /tutorials/data-tutorial.html

### ISSUE THREAD

**Issue by henrydingliu** [casact/chainladder-python#301] opened 2022-05-24 07:33 UTC
error at the bottom of the page

`plt.plot(
    (model_cl.ultimate_["Paid"]).to_frame().index.astype("string"),
    (model_cl.ultimate_["Paid"] / model_cl.ultimate_["reportedCount"]).to_frame(),
)`
`plt.xticks(np.arange(0, 10 * 12, 12), np.arange(2008, 2018, 1))`

**Comment by kennethshsu** [comment] 2022-05-26 14:20
@jbogaardt do you know why the [read the docs page](https://chainladder-python.readthedocs.io/en/latest/tutorials/data-tutorial.html) is still showing the error even though the [source file](https://github.com/casact/chainladder-python/blob/master/docs/tutorials/data-tutorial.ipynb) is good? How do you rebuild the page? I thought it's automatic?

**Comment by jbogaardt** [comment] 2022-05-26 14:25
It is automatic, these are the most recent successful builds:
![image](https://user-images.githubusercontent.com/19401133/170507820-ef13b486-9121-4f54-91cb-39c7f52a19ec.png)
If you're looking at the stable docs, they are only updated upon a release of chainladder-python. Howeverm the "latest" and "master" versions of the docs should have your updates.

**Comment by jbogaardt** [comment] 2022-05-26 20:24
i just removed those lines, so if it was causing the fails in the tutorial, then they should rebuild correctly.

On `__version__`, I guess we can add a 'b'. Version 0.8.13 is not available through Pypi, I've always looked at any differences between master and pypi as beta changes for any package I use, but there is nothing wrong with being explicit.

**Comment by jbogaardt** [comment] 2022-05-26 21:40
still showing error using the following setup:
pandas: 1.4.2
numpy: 1.21.5
chainladder: 0.8.13

The committed notebook shows chainladder 0.8.12. This may have regressed earlier or it could be pandas==1.4.2.

**Comment by kennethshsu** [comment] 2022-06-25 00:30
@jbogaardt I think I know what the problem is now...

The master branch on github should always match the released version. Can we make another release of `0.8.13`? readthedocs will re-execute the code in the docs folder, and that means currently the tutorials (and all example exhibits) will be rebuilt using the `0.8.12` version of chainladder.

We have at least two ways to address this:
1. Release `0.8.13` and see if that fixes it.
2. Don't rebuild the jupyter notebook in readthedocs. We can change the `execute_notebooks` parameter inside [_config.yml](https://github.com/casact/chainladder-python/blob/master/docs/_config.yml) from `force` to `'off'` (with quotes?! [documentation](https://jupyterbook.org/en/stable/content/execute.html)). I think this will just published the notebook using the cached values.
3. Have a branch that tracks the released package, currently it is on `0.8.12`, and modify the build command `[here](https://readthedocs.org/projects/chainladder-python/builds/17258110/)` by checking out the specified branch.

I don't know which one is better, what do you think?

**Comment by kennethshsu** [comment] 2022-06-25 00:30
@jbogaardt I think I know what the problem is now...

The master branch on github should always match the released version. Can we make another release of `0.8.13`? readthedocs will re-execute the code in the docs folder, and that means currently the tutorials (and all example exhibits) will be rebuilt using the `0.8.12` version of chainladder.

We have at least a few ways to address this:
1. Release `0.8.13` and see if that fixes it.
2. Don't rebuild the jupyter notebook in readthedocs. We can change the `execute_notebooks` parameter inside [_config.yml](https://github.com/casact/chainladder-python/blob/master/docs/_config.yml) from `force` to `'off'` (with quotes?! [documentation](https://jupyterbook.org/en/stable/content/execute.html)). I think this will just published the notebook using the cached values.
3. Have a branch that tracks the released package, currently it is on `0.8.12`, and modify the build command `[here](https://readthedocs.org/projects/chainladder-python/builds/17258110/)` by checking out the specified branch.

I don't know which one is better, what do you think?

**Comment by kennethshsu** [comment] 2022-06-25 00:37
Hmm looking at #3 in a bit more detail, I think it actually checkouts the master code, which should be `0.8.13`...

**Comment by jbogaardt** [comment] 2022-06-25 01:06
Readthedocs builds several versions of the docs and they can be accessed by the end user here:
![image](https://user-images.githubusercontent.com/19401133/175752421-aed42995-0bd0-4028-afa2-0a0713756975.png)


Stable = latest stable release
Master = latest commit on master
Latest = latest commit on some other specified branch (which we default to master)

**Comment by kennethshsu** [comment] 2022-06-25 04:07
Do you see 0.8.12 on stable? I see 0.8.10 instead.

**Comment by jbogaardt** [comment] 2022-06-26 12:42
You're right. I see what you mean. The stable docs have been failing since 0.8.10 for the same reasons. The commits they rely on are not working, so I'll try to get 0.8.13 released today for a more up-to-date stable docs.

**Comment by kennethshsu** [comment] 2022-06-29 05:21
I think everything is on 0.8.13 now, but the code is still not compiling correctly. Do you think it makes sense to try changing the [_config.yml](https://github.com/casact/chainladder-python/blob/master/docs/_config.yml) file?

**Comment by jbogaardt** [comment] 2022-06-29 11:47
The builds are all passing. I believe any remaining issues are dependency conflicts. I get the same errors on the data-tutorial in my cl_docs environment locally that I shows on the website.

**Closed** 2022-11-16 23:08 UTC
Labels: Documentation
