### ISSUE TITLE
mid-year valuations not working

### ISSUE THREAD

**Issue by goduckie** [casact/chainladder-python#225] opened 2021-11-04 01:31 UTC
see code example below:

```
import chainladder as cl
import pandas as pd

raa = cl.load_sample('raa')\
    .dev_to_val()\
    .to_frame(keepdims=True)

#adjust valuations to mid-year
raa['valuation'] = raa['valuation']-raa.apply(lambda x: pd.DateOffset(**{'months': 6}), axis=1)

def kwargs(df):
    return {'data': raa.reset_index(),
            'columns': 'values',
            'origin': 'origin',
            'development': 'valuation',
            'index': 'Total',
            'cumulative': True}

#ERROR expecting tri development at 6, 18, 30 etc
tri = cl.Triangle(**kwargs(raa))

#ERROR adjusted mid-year valuations are overwritten with EOY
tri.dev_to_val().to_frame(keepdims=True)
```

**Comment by goduckie** [comment] 2021-11-04 02:09
a triangle with just latest diagonal works as expected:

i..e replace the first line with the following, results in development periods at 6, 18, 30 etc

```
raa = cl.load_sample('raa')\
    .dev_to_val()\
    .latest_diagonal\
    .to_frame(keepdims=True)

```

**Comment by jbogaardt** [comment] 2021-11-04 02:44
This is definitely a gap in the library.  OYDY grains with support for ages other than ages 12, 24, 36, etc. is spotty.  This is a big problem, particularly for reinsurance or consulting where get pre-aggregated data is common. Its definitely an enhancement we need to tackle.

**Comment by goduckie** [comment] 2021-11-04 03:21
Can you please help me understand, why it even cares what the ages are? 

Provided the ages are consistent between development and the triangle that is being transformed / fitted, then shouldn't the ages themselves be irrelevant? What am I not understanding?

**Comment by jbogaardt** [comment] 2021-11-04 12:17
It shouldn't, but thats not the tricky part.  The tricky part is that we need to accomodate two different use cases here.
1. Yours is one that requires that the origin periods follow a January-December with an age of 6, 18, ... 
2. Others want a July-June origin period assuming age 12, 24, ...

Ensuring that enough information is obtained from the data and user to support both is something that needs to be thought out.

By the way, this one is a duplicate of #188, so it's on the list of things to do.  We should close one of the duplicates out.

**Comment by AuldKingCole** [comment] 2021-11-11 14:52
I'm actually facing this very problem right now in attempting to apply this library to my work as a reinsurer. The industry benchmarks that I'm provided are evaluated each March, with the first evaluation for a given accident year starting at 15 months. I can't for the life of me get the cl.Triangle() to produce a triangle on a 15/27/39 etc. basis. It keeps overwriting my development entries and assuming annual evaluation delays. Any advice or solutions would be greatly appreciated.

**Comment by jbogaardt** [comment] 2021-11-11 15:28
@AuldKingCole, unfortunately I don't have a solution that isn't completely janky.  I run into the same problem using industry data at those same valuations.  I appreciate you sharing your pain point as well.  The only consolation I can give is that the higher number of people wanting this functionality definitely influences its prioritization.  We can prioritize it for the next release. Unfortunately that is not days/weeks in the making. Realistically it would be more like late December.

**Comment by AuldKingCole** [comment] 2021-11-11 15:34
@jbogaardt , thanks for the response. While I see so much potential for this library in some projects I would like to establish down the line, in the meantime I only need a crisp means of batch calculating link ratios and averages. I suppose for now it won't matter if I allow the triangles to default to 12-24-36 etc? I will be very very interested in utilizing this library further if the mid-year issue ever gets worked out.

**Comment by jbogaardt** [comment] 2021-11-11 16:45
@AuldKingCole, It makes me cringe that anyone would have to do that, but that should be fine for estimating LDFs.

**Closed** 2021-12-05 14:16 UTC
